const PROJECT_STATUSES = Object.freeze({
    CREATED: 'CREATED',
    AUDIT_PENDING: 'AUDIT_PENDING',
    AUDITING: 'AUDITING',
    AUDIT_COMPLETE: 'AUDIT_COMPLETE',
    REWRITE_PENDING: 'REWRITE_PENDING',
    REWRITING: 'REWRITING',
    REWRITE_COMPLETE: 'REWRITE_COMPLETE',
    REVIEW_PENDING: 'REVIEW_PENDING',
    DRAFT_CREATED: 'DRAFT_CREATED',
    READY_FOR_EDITOR: 'READY_FOR_EDITOR',
    COMPLETED: 'COMPLETED',
    ARCHIVED: 'ARCHIVED',
    FAILED: 'FAILED'
});

const VALID_PROJECT_TRANSITIONS = {
    [PROJECT_STATUSES.CREATED]: [PROJECT_STATUSES.AUDIT_PENDING, PROJECT_STATUSES.REWRITE_PENDING, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.AUDIT_PENDING]: [PROJECT_STATUSES.AUDITING, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.AUDITING]: [PROJECT_STATUSES.AUDIT_COMPLETE, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.AUDIT_COMPLETE]: [PROJECT_STATUSES.REWRITE_PENDING, PROJECT_STATUSES.REVIEW_PENDING, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.REWRITE_PENDING]: [PROJECT_STATUSES.REWRITING, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.REWRITING]: [PROJECT_STATUSES.REWRITE_COMPLETE, PROJECT_STATUSES.REWRITE_PENDING, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.REWRITE_COMPLETE]: [PROJECT_STATUSES.REVIEW_PENDING, PROJECT_STATUSES.DRAFT_CREATED, PROJECT_STATUSES.READY_FOR_EDITOR, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.REVIEW_PENDING]: [PROJECT_STATUSES.DRAFT_CREATED, PROJECT_STATUSES.READY_FOR_EDITOR, PROJECT_STATUSES.COMPLETED, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.DRAFT_CREATED]: [PROJECT_STATUSES.READY_FOR_EDITOR, PROJECT_STATUSES.COMPLETED, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.READY_FOR_EDITOR]: [PROJECT_STATUSES.COMPLETED, PROJECT_STATUSES.FAILED],
    [PROJECT_STATUSES.COMPLETED]: [PROJECT_STATUSES.ARCHIVED],
    [PROJECT_STATUSES.FAILED]: [PROJECT_STATUSES.AUDIT_PENDING, PROJECT_STATUSES.REWRITE_PENDING, PROJECT_STATUSES.REVIEW_PENDING], // Allow retry
    [PROJECT_STATUSES.ARCHIVED]: []
};

class ContentProject {
    constructor(data) {
        this.id = data.id;
        this.siteId = data.site_id;
        this.wpPostId = data.wp_post_id;
        this.status = data.status;
        this.createdAt = data.created_at;
        this.updatedAt = data.updated_at;
    }

    static isValidTransition(from, to) {
        if (!VALID_PROJECT_TRANSITIONS[from]) return false;
        return VALID_PROJECT_TRANSITIONS[from].includes(to);
    }
}

module.exports = { ContentProject, PROJECT_STATUSES };
